local DensityMultiplier = 0.1

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)

        SetVehicleDensityMultiplierThisFrame(DensityMultiplier)
        SetRandomVehicleDensityMultiplierThisFrame(DensityMultiplier)
        SetParkedVehicleDensityMultiplierThisFrame(DensityMultiplier)

        SetPedDensityMultiplierThisFrame(0.0)
        SetScenarioPedDensityMultiplierThisFrame(0.0, 0.0)

		SetVehicleModelIsSuppressed(GetHashKey("akuma"), true)
		SetVehicleModelIsSuppressed(GetHashKey("bati"), true)
		SetVehicleModelIsSuppressed(GetHashKey("bati2"), true)
		SetVehicleModelIsSuppressed(GetHashKey("carbonrs"), true)
		SetVehicleModelIsSuppressed(GetHashKey("double"), true)
		SetVehicleModelIsSuppressed(GetHashKey("hakuchou"), true)
		SetVehicleModelIsSuppressed(GetHashKey("hakuchou2"), true)
		SetVehicleModelIsSuppressed(GetHashKey("nemesis"), true)
		SetVehicleModelIsSuppressed(GetHashKey("vader"), true)
		SetVehicleModelIsSuppressed(GetHashKey("defiler"), true)
		SetVehicleModelIsSuppressed(GetHashKey("lectro"), true)
		SetVehicleModelIsSuppressed(GetHashKey("shotaro"), true)
		SetVehicleModelIsSuppressed(GetHashKey("stryder"), true)
		SetVehicleModelIsSuppressed(GetHashKey("manchez2"), true)

		SetVehicleModelIsSuppressed(GetHashKey("sanchez"), true)
		SetVehicleModelIsSuppressed(GetHashKey("sanchez2"), true)
		SetVehicleModelIsSuppressed(GetHashKey("manchez"), true)
		SetVehicleModelIsSuppressed(GetHashKey("rrocket"), true)
		SetVehicleModelIsSuppressed(GetHashKey("esskey"), true)

		SetVehicleModelIsSuppressed(GetHashKey("avarus"), true)
		SetVehicleModelIsSuppressed(GetHashKey("bagger"), true)
		SetVehicleModelIsSuppressed(GetHashKey("chimera"), true)
		SetVehicleModelIsSuppressed(GetHashKey("cliffhanger"), true)
		SetVehicleModelIsSuppressed(GetHashKey("daemon"), true)
		SetVehicleModelIsSuppressed(GetHashKey("daemon2"), true)
		SetVehicleModelIsSuppressed(GetHashKey("faggio"), true)
		SetVehicleModelIsSuppressed(GetHashKey("faggio2"), true)
		SetVehicleModelIsSuppressed(GetHashKey("faggio3"), true)
		SetVehicleModelIsSuppressed(GetHashKey("gargoyle"), true)
		SetVehicleModelIsSuppressed(GetHashKey("innovation"), true)
		SetVehicleModelIsSuppressed(GetHashKey("nightblade"), true)
		SetVehicleModelIsSuppressed(GetHashKey("oppressor"), true)
		SetVehicleModelIsSuppressed(GetHashKey("oppressor2"), true)
		SetVehicleModelIsSuppressed(GetHashKey("pcj"), true)
		SetVehicleModelIsSuppressed(GetHashKey("ratbike"), true)
		SetVehicleModelIsSuppressed(GetHashKey("reever"), true)
		SetVehicleModelIsSuppressed(GetHashKey("ruffian"), true)
		SetVehicleModelIsSuppressed(GetHashKey("sanctus"), true)
		SetVehicleModelIsSuppressed(GetHashKey("sovereign"), true)
		SetVehicleModelIsSuppressed(GetHashKey("thrust"), true)
		SetVehicleModelIsSuppressed(GetHashKey("vindicator"), true)
		SetVehicleModelIsSuppressed(GetHashKey("wolfsbane"), true)
		SetVehicleModelIsSuppressed(GetHashKey("zombiea"), true)
		SetVehicleModelIsSuppressed(GetHashKey("zombieb"), true)

    end
end)